# Generated by Django 3.2.3 on 2021-06-07 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='woodmodel',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
