# Generated by Django 3.2.3 on 2021-06-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='woodmodel',
            name='surface',
            field=models.IntegerField(default=0, verbose_name='贴皮数'),
        ),
    ]
