# Generated by Django 3.2.3 on 2021-06-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0002_woodmodel_created_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WoodFormModel',
        ),
    ]
