# Generated by Django 3.2.3 on 2021-06-12 02:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0003_delete_woodformmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='woodmodel',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间'),
        ),
    ]
