# Generated by Django 3.2.3 on 2021-06-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0004_alter_woodmodel_surface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='woodmodel',
            name='surface',
        ),
    ]
