# Generated by Django 3.2.3 on 2021-06-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0004_woodmodel_last_mod_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='woodmodel',
            old_name='is_enable',
            new_name='enable',
        ),
    ]
