# Generated by Django 3.2.3 on 2021-06-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationmodel',
            name='note',
            field=models.TextField(default='', max_length=256, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='technologymodel',
            name='note',
            field=models.TextField(default='', max_length=256, verbose_name='备注'),
        ),
    ]
