# Generated by Django 3.2.3 on 2021-06-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationmodel',
            name='last_mod_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='technologymodel',
            name='last_mod_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
