# Generated by Django 3.2.3 on 2021-06-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20210612_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificationmodel',
            old_name='is_enable',
            new_name='enable',
        ),
        migrations.RenameField(
            model_name='technologymodel',
            old_name='is_enable',
            new_name='enable',
        ),
    ]
