# Generated by Django 3.2.3 on 2021-06-02 17:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('salesman', '0001_initial'),
        ('skin', '0001_initial'),
        ('account', '0001_initial'),
        ('paper', '0001_initial'),
        ('process', '0001_initial'),
        ('wood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=64, verbose_name='日期')),
                ('woodCount', models.TextField(max_length=64, verbose_name='木料数量')),
                ('skinCount', models.TextField(max_length=64, verbose_name='桉木皮数量')),
                ('paperCount', models.TextField(max_length=64, verbose_name='纸张数量')),
                ('color', models.TextField(max_length=64, verbose_name='花色')),
                ('packaging', models.TextField(max_length=64, verbose_name='包装')),
                ('thickness', models.TextField(max_length=64, verbose_name='厚度')),
                ('trademark', models.TextField(max_length=64, verbose_name='商标')),
                ('word', models.TextField(max_length=64, verbose_name='打字')),
                ('is_grooving', models.BooleanField(default=True, verbose_name='是否开槽')),
                ('is_drying', models.BooleanField(default=True, verbose_name='是否烘干')),
                ('is_sure', models.BooleanField(default=True, verbose_name='是否确认')),
                ('sure_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='确认时间')),
                ('is_complete', models.BooleanField(default=True, verbose_name='是否完成')),
                ('complete_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='完成时间')),
                ('note', models.TextField(max_length=256, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customermodel', verbose_name='厂家')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paper.papermodel', verbose_name='纸张')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesman.salesmanmodel', verbose_name='销售员')),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skin.skinmodel', verbose_name='桉木皮')),
                ('specifications', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.specificationmodel', verbose_name='规格')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.technologymodel', verbose_name='钢铁工艺')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.accountmodel', verbose_name='作者')),
                ('wood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wood.woodmodel', verbose_name='材质')),
            ],
        ),
    ]
