# Generated by Django 3.2.3 on 2021-06-13 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wood', '0001_initial'),
        ('customer', '0001_initial'),
        ('process', '0001_initial'),
        ('salesman', '0001_initial'),
        ('skin', '0001_initial'),
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.DateField(default=django.utils.timezone.now, verbose_name='下单时间')),
                ('delivery_time', models.DateField(default=django.utils.timezone.now, verbose_name='交货时间')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('woodCount', models.IntegerField(default=0, verbose_name='木料数量')),
                ('skinCount', models.IntegerField(default=0, verbose_name='桉木皮数量')),
                ('paperCount', models.IntegerField(default=0, verbose_name='纸张数量')),
                ('color', models.TextField(max_length=64, verbose_name='花色')),
                ('packaging', models.TextField(default='', max_length=64, verbose_name='包装')),
                ('thickness', models.TextField(default='', max_length=64, verbose_name='厚度')),
                ('trademark', models.TextField(default='', max_length=64, verbose_name='商标')),
                ('word', models.TextField(default='', max_length=64, verbose_name='打字')),
                ('is_grooving', models.BooleanField(default=False, verbose_name='是否开槽')),
                ('is_drying', models.BooleanField(default=False, verbose_name='是否烘干')),
                ('sure', models.BooleanField(default=False, verbose_name='是否确认')),
                ('complete', models.BooleanField(default=False, verbose_name='是否完成')),
                ('note', models.TextField(default='', max_length=256, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customermodel', verbose_name='厂家')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paper.papermodel', verbose_name='纸张')),
                ('salesman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='salesman.salesmanmodel', verbose_name='销售员')),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skin.skinmodel', verbose_name='桉木皮')),
                ('specifications', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.specificationmodel', verbose_name='规格')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.technologymodel', verbose_name='钢板工艺')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('wood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wood.woodmodel', verbose_name='木料')),
            ],
        ),
        migrations.CreateModel(
            name='WoodFormModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arrive_time', models.DateField(default=django.utils.timezone.now, verbose_name='到货时间')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('type', models.CharField(choices=[('1', '入库'), ('2', '出库'), ('3', '损耗')], default='1', max_length=4, verbose_name='类型')),
                ('sure', models.BooleanField(default=False, verbose_name='是否确认')),
                ('complete', models.BooleanField(default=False, verbose_name='是否完成')),
                ('note', models.TextField(default='', max_length=256, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wood.woodmodel', verbose_name='木料')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ordermodel', verbose_name='关联订单')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='SkinFormModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arrive_date', models.DateField(default=django.utils.timezone.now, verbose_name='到货时间')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('type', models.CharField(choices=[('1', '入库'), ('2', '出库'), ('3', '损耗')], default='1', max_length=4, verbose_name='类型')),
                ('sure', models.BooleanField(default=False, verbose_name='是否确认')),
                ('complete', models.BooleanField(default=False, verbose_name='是否完成')),
                ('note', models.TextField(default='', max_length=256, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skin.skinmodel', verbose_name='桉木皮')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ordermodel', verbose_name='关联订单')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='PaperFormModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('factory', models.TextField(max_length=64, verbose_name='厂家')),
                ('arrive_time', models.TextField(default=django.utils.timezone.now, verbose_name='到货时间')),
                ('type', models.CharField(choices=[('1', '入库'), ('2', '出库'), ('3', '损耗')], default='1', max_length=4, verbose_name='类型')),
                ('sure', models.BooleanField(default=False, verbose_name='是否确认')),
                ('complete', models.BooleanField(default=False, verbose_name='是否确认')),
                ('note', models.TextField(default='', max_length=256, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paper.papermodel', verbose_name='纸张')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ordermodel', verbose_name='关联订单')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
    ]
