# Generated by Django 3.2.3 on 2021-06-12 01:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0002_delete_skinformmodel'),
        ('wood', '0003_delete_woodformmodel'),
        ('paper', '0002_delete_paperformmodel'),
        ('account', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoodFormModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('type', models.CharField(choices=[('1', '入库'), ('2', '出库'), ('3', '损耗')], default='1', max_length=10, verbose_name='类型')),
                ('is_sure', models.BooleanField(default=True, verbose_name='是否确认')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wood.woodmodel', verbose_name='木料')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordermodel', verbose_name='关联订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.accountmodel', verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='SkinFormModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('type', models.CharField(choices=[('1', '入库'), ('2', '出库'), ('3', '损耗')], default='1', max_length=10, verbose_name='类型')),
                ('is_sure', models.BooleanField(default=True, verbose_name='是否确认')),
                ('note', models.TextField(max_length=256, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordermodel', verbose_name='关联订单')),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skin.skinmodel', verbose_name='桉木皮')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.accountmodel', verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='PaperFormModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('factory', models.TextField(max_length=64, verbose_name='厂家')),
                ('arrive_time', models.TextField(default=django.utils.timezone.now, verbose_name='到货时间')),
                ('type', models.CharField(choices=[('1', '入库'), ('2', '出库'), ('3', '损耗')], default='1', max_length=10, verbose_name='类型')),
                ('is_sure', models.BooleanField(default=True, verbose_name='是否确认')),
                ('note', models.TextField(max_length=256, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordermodel', verbose_name='关联订单')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paper.papermodel', verbose_name='纸张')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.accountmodel', verbose_name='作者')),
            ],
        ),
    ]
