# Generated by Django 3.2.3 on 2021-06-13 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='delivery_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='交货时间'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='下单时间'),
        ),
        migrations.AlterField(
            model_name='skinformmodel',
            name='arrive_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='到货时间'),
        ),
        migrations.AlterField(
            model_name='woodformmodel',
            name='arrive_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='到货时间'),
        ),
    ]
