# Generated by Django 3.2.3 on 2021-06-13 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210614_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperformmodel',
            name='arrive_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='到货时间'),
        ),
        migrations.AlterField(
            model_name='paperformmodel',
            name='type',
            field=models.CharField(choices=[('1', '入库'), ('2', '出库'), ('3', '损耗'), ('4', '订单')], default='1', max_length=4, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='skinformmodel',
            name='type',
            field=models.CharField(choices=[('1', '入库'), ('2', '出库'), ('3', '损耗'), ('4', '订单')], default='1', max_length=4, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='woodformmodel',
            name='type',
            field=models.CharField(choices=[('1', '入库'), ('2', '出库'), ('3', '损耗'), ('4', '订单')], default='1', max_length=4, verbose_name='类型'),
        ),
    ]
