# Generated by Django 3.2.3 on 2021-06-12 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_paperformmodel_skinformmodel_woodformmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinformmodel',
            name='arrive_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='到货时间'),
        ),
        migrations.AddField(
            model_name='woodformmodel',
            name='arrive_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='到货时间'),
        ),
        migrations.AddField(
            model_name='woodformmodel',
            name='note',
            field=models.TextField(default='', max_length=256, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='paperformmodel',
            name='note',
            field=models.TextField(default='', max_length=256, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='paperformmodel',
            name='type',
            field=models.CharField(choices=[('1', '入库'), ('2', '出库'), ('3', '损耗')], default='1', max_length=4, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='skinformmodel',
            name='note',
            field=models.TextField(default='', max_length=256, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='skinformmodel',
            name='type',
            field=models.CharField(choices=[('1', '入库'), ('2', '出库'), ('3', '损耗')], default='1', max_length=4, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='woodformmodel',
            name='type',
            field=models.CharField(choices=[('1', '入库'), ('2', '出库'), ('3', '损耗')], default='1', max_length=4, verbose_name='类型'),
        ),
    ]
