# Generated by Django 3.2.3 on 2021-06-12 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210612_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woodformmodel',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ordermodel', verbose_name='关联订单'),
        ),
    ]
