# Generated by Django 3.2.3 on 2021-06-14 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210614_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='下单时间'),
        ),
    ]
