# Generated by Django 3.2.3 on 2021-06-12 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('order', '0004_alter_woodformmodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woodformmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.accountmodel', verbose_name='作者'),
        ),
    ]
