# Generated by Django 3.2.3 on 2021-06-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_woodformmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='is_complete',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='is_sure',
            new_name='sure',
        ),
        migrations.RenameField(
            model_name='paperformmodel',
            old_name='is_sure',
            new_name='sure',
        ),
        migrations.RenameField(
            model_name='skinformmodel',
            old_name='is_sure',
            new_name='sure',
        ),
        migrations.RenameField(
            model_name='woodformmodel',
            old_name='is_sure',
            new_name='sure',
        ),
    ]
