# Generated by Django 3.2.3 on 2021-06-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210615_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperformmodel',
            old_name='arrive_time',
            new_name='arrive_date',
        ),
        migrations.RenameField(
            model_name='woodformmodel',
            old_name='arrive_time',
            new_name='arrive_date',
        ),
    ]
