# Generated by Django 3.2.3 on 2021-06-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210613_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='note',
            field=models.TextField(default='', max_length=256, verbose_name='备注'),
        ),
    ]
