# Generated by Django 3.2.3 on 2021-06-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210615_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='delivery_time',
            new_name='delivery_date',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='order_time',
            new_name='order_date',
        ),
    ]
