# Generated by Django 3.2.3 on 2021-06-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_ordermodel_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperformmodel',
            old_name='paper',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='skinformmodel',
            old_name='skin',
            new_name='name',
        ),
    ]
