# Generated by Django 3.2.3 on 2021-06-12 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('order', '0008_auto_20210613_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperformmodel',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ordermodel', verbose_name='关联订单'),
        ),
        migrations.AlterField(
            model_name='paperformmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.accountmodel', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='skinformmodel',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ordermodel', verbose_name='关联订单'),
        ),
        migrations.AlterField(
            model_name='skinformmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.accountmodel', verbose_name='作者'),
        ),
    ]
