# Generated by Django 3.2.3 on 2021-06-17 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0003_skinmodel_factory'),
        ('paper', '0003_auto_20210618_0709'),
        ('order', '0008_auto_20210615_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='count',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='other_paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_paper', to='paper.papermodel', verbose_name='纸张2'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paper.papermodel', verbose_name='纸张1'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='skin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='skin.skinmodel', verbose_name='桉木皮'),
        ),
    ]
