# Generated by Django 3.2.3 on 2021-06-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210618_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='other_paper_count',
            field=models.IntegerField(default=0, verbose_name='纸张数量'),
        ),
    ]
