# Generated by Django 3.2.3 on 2021-06-17 23:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210614_0133'),
        ('salesman', '0002_alter_salesmanmodel_name'),
        ('order', '0010_ordermodel_other_paper_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHeadModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.DateField(default=django.utils.timezone.now, verbose_name='订单编号')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='下单时间')),
                ('delivery_date', models.DateField(default=django.utils.timezone.now, verbose_name='交货时间')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customermodel', verbose_name='厂家')),
                ('salesman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='salesman.salesmanmodel', verbose_name='销售员')),
            ],
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='head_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='order.orderheadmodel', verbose_name='订单编号'),
        ),
    ]
