# Generated by Django 3.2.3 on 2021-06-19 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0011_auto_20210618_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default=0, verbose_name='订单编号')),
            ],
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='salesman',
        ),
        migrations.AddField(
            model_name='orderheadmodel',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
        migrations.AddField(
            model_name='orderheadmodel',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='orderheadmodel',
            name='last_mod_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='orderheadmodel',
            name='note',
            field=models.TextField(default='', max_length=256, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='orderheadmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='orderheadmodel',
            name='order_number',
            field=models.IntegerField(default=0, verbose_name='订单编号'),
        ),
    ]
