# Generated by Django 3.2.3 on 2021-06-19 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210619_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernumbermodel',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='下单时间'),
        ),
    ]
