# Generated by Django 3.2.3 on 2021-06-27 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0003_skinmodel_factory'),
        ('paper', '0003_auto_20210618_0709'),
        ('order', '0013_ordernumbermodel_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='note',
            field=models.TextField(blank=True, default='', max_length=256, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='other_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_paper', to='paper.papermodel', verbose_name='纸张2'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='other_paper_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='纸张数量'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='packaging',
            field=models.TextField(blank=True, default='', max_length=64, verbose_name='包装'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='paper.papermodel', verbose_name='纸张1'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='paperCount',
            field=models.IntegerField(blank=True, default=0, verbose_name='纸张数量'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='skin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='skin.skinmodel', verbose_name='桉木皮'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='skinCount',
            field=models.IntegerField(blank=True, default=0, verbose_name='桉木皮数量'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='thickness',
            field=models.TextField(blank=True, default='', max_length=64, verbose_name='厚度'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='trademark',
            field=models.TextField(blank=True, default='', max_length=64, verbose_name='商标'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='word',
            field=models.TextField(blank=True, default='', max_length=64, verbose_name='打字'),
        ),
    ]
