# Generated by Django 3.2.3 on 2021-07-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20210628_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernumbermodel',
            name='order_date',
            field=models.IntegerField(default=0, verbose_name='下单时间'),
        ),
    ]
