# Generated by Django 3.2.3 on 2021-07-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_ordernumbermodel_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernumbermodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
