# Generated by Django 3.2.3 on 2021-07-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_ordernumbermodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheadmodel',
            name='sure',
            field=models.BooleanField(default=False, verbose_name='是否确认'),
        ),
    ]
