# Generated by Django 3.2.3 on 2021-07-03 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_orderheadmodel_sure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderheadmodel',
            name='delivery_date',
            field=models.DateField(default=datetime.date, verbose_name='交货时间'),
        ),
        migrations.AlterField(
            model_name='orderheadmodel',
            name='order_date',
            field=models.DateField(default=datetime.date, verbose_name='下单时间'),
        ),
    ]
