# Generated by Django 3.2.3 on 2021-07-03 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20210704_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderheadmodel',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='交货时间'),
        ),
        migrations.AlterField(
            model_name='orderheadmodel',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='下单时间'),
        ),
    ]
