# Generated by Django 3.2.3 on 2021-07-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20210704_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='index',
            field=models.IntegerField(blank=True, default=1, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
