# Generated by Django 3.2.3 on 2021-07-15 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0005_alter_skinmodel_name'),
        ('order', '0023_auto_20210708_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='other_skin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_skin', to='skin.skinmodel', verbose_name='桉木皮2'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='other_skin_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='桉木皮数量2'),
        ),
    ]
