# Generated by Django 3.2.3 on 2021-07-16 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20210715_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperformmodel',
            name='factory',
        ),
    ]
