# Generated by Django 3.2.3 on 2021-06-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='是否使用'),
        ),
    ]
