# Generated by Django 3.2.3 on 2021-06-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0002_delete_skinformmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skinmodel',
            old_name='is_enable',
            new_name='enable',
        ),
    ]
