# Generated by Django 3.2.3 on 2021-06-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0003_skinmodel_factory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinmodel',
            name='name',
            field=models.TextField(max_length=64, verbose_name='名称'),
        ),
    ]
