# Generated by Django 3.2.3 on 2021-06-02 17:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=64, verbose_name='名称')),
                ('type', models.TextField(max_length=64, verbose_name='型号')),
                ('factory', models.TextField(max_length=64, verbose_name='厂家')),
                ('arrive_time', models.TextField(default=django.utils.timezone.now, verbose_name='到货时间')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否禁用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='PaperFormModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('factory', models.TextField(max_length=64, verbose_name='厂家')),
                ('arrive_time', models.TextField(default=django.utils.timezone.now, verbose_name='到货时间')),
                ('type', models.CharField(choices=[('1', '入库'), ('2', '出库'), ('3', '损耗')], default='1', max_length=10, verbose_name='类型')),
                ('is_sure', models.BooleanField(default=True, verbose_name='是否确认')),
                ('note', models.TextField(max_length=256, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paper.papermodel', verbose_name='纸张')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.accountmodel', verbose_name='作者')),
            ],
        ),
    ]
