# Generated by Django 3.2.3 on 2021-06-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaperFormModel',
        ),
    ]
