# Generated by Django 3.2.3 on 2021-06-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_delete_paperformmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papermodel',
            old_name='is_enable',
            new_name='enable',
        ),
    ]
