# Generated by Django 3.2.3 on 2021-06-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_rename_is_enable_papermodel_enable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papermodel',
            name='arrive_time',
        ),
        migrations.AddField(
            model_name='papermodel',
            name='note',
            field=models.TextField(default='', max_length=256, verbose_name='备注'),
        ),
    ]
