# Generated by Django 3.2.3 on 2021-06-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='note',
            field=models.TextField(default='', max_length=256, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='name',
            field=models.TextField(max_length=64, unique=True, verbose_name='名称'),
        ),
    ]
