# Generated by Django 3.2.3 on 2021-06-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_is_enable_customermodel_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='note',
            field=models.TextField(default='', max_length=256, verbose_name='备注'),
        ),
    ]
