# Generated by Django 3.2.3 on 2021-06-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesmanmodel',
            old_name='is_enable',
            new_name='enable',
        ),
        migrations.AddField(
            model_name='salesmanmodel',
            name='note',
            field=models.TextField(default='', max_length=256, verbose_name='备注'),
        ),
    ]
